services:
  web:
    build: .
    image: $RUBY_VERSION-slim
    command: ./bin/rails server -p 3000 -b '0.0.0.0'
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV}
      APP_USER: ${DB_USERNAME}
      APP_USER_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: postgres://${DB_USERNAME}:@db:5432/${DB_NAME}

  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/docker/volumes/dev_portfolio_v2_db/_data
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
      APP_USER: ${DB_USERNAME}
      APP_USER_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres_data: